# Copyright 2024 Cisco Systems, Inc. and its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

#----------------------------------------------------------------------------------------
# Device inventory and collection configuration file
# for Cisco Sustainability Insights
#----------------------------------------------------------------------------------------
loglevel:
  console: INFO
sites:
  branch:
    Latitude: '14.59'
    Longitude: '120.98'
    Timezone: Asia/Manila
    avg_co2_intensity: 570
  campus:
    Latitude: '37.375'
    Longitude: '-6.037'
    Timezone: Europe/Madrid
    avg_co2_intensity: 60
devices:
  ASR1k-A:
    site: branch
    family: ASR1k
    os_type: iosxe
    os_version: Unknown
    connection: ssh
    address: 10.10.0.1
    port: 22
    username: admin
    password: password-encrypted-on-first-run
    timeout: 30
    collection:
      enabled: true
      interval: 10
  C9300-B:
    site: campus
    family: Cat9300
    os_type: iosxe
    os_version: Unknown
    connection: ssh
    address: 10.20.0.1
    port: 22
    username: admin
    password: another-password-encrypted-on-first-run
    timeout: 30
    collection:
      enabled: true
      interval: 10
